homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 54
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages
  
  
# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  themes: !include_dir_named themes
  extra_html_url:
    - /local/custom_ui/state-card-floorplan.html

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

#panel_custom:
#  - name: floorplan
#    sidebar_title: Floorplan
#    sidebar_icon: mdi:home
#    url_path: floorplan
#    config: !include floorplan.yaml

# Enables a map showing the location of tracked devices
#map:


twilio:
  account_sid: !secret account_twilio
  auth_token: !secret token_twilio

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
    name: Weather
    forecast: 24
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
  - platform: hue
    ip_address: 192.168.0.14
    token: !secret hue_token
    scan_interval: 2
  - platform: miflora
    mac: 'C4:7C:8D:66:EA:94'
    name: "blomma1"
    median: 1
  - platform: miflora
    mac: 'C4:7C:8D:66:EA:97'
    name: "blomma2"
    median: 1
  - platform: miflora
    mac: 'C4:7C:8D:66:EA:B4'
    name: "blomma3"
    median: 1
  - platform: miflora
    mac: 'C4:7C:8D:66:EA:B6'
    name: "blomma4"
    median: 1
  - platform: miflora
    mac: 'C4:7C:8D:66:EA:CD'
    name: "blomma5"
    median: 1
  - platform: miflora
    mac: 'C4:7C:8D:66:EA:D1'
    name: "blomma6"
    median: 1
  - platform: miflora
    mac: 'C4:7C:8D:66:EB:07'
    name: "blomma7"
    median: 1
  - platform: miflora
    mac: 'C4:7C:8D:66:EB:1B'
    name: "blomma8"
    median: 1



light:
  - platform: yeelight
    devices:
      192.168.0.19:
        name: Yeelight
        model: bslamp1
  - platform: switch
    entity_id: switch.banklampa_sovrum
    name: Bedroom table
  - platform: switch
    entity_id: switch.fonsterlampa_sovrum
    name: Bedroom window
  - platform: switch
    entity_id: switch.golvlampa_sovrum
    name: Bedroom floor
  - platform: switch
    entity_id: switch.vardagsrumsfonster
    name: Living room window lamps
# Text to speech
#tts:
#  - platform: google

# Cloud
cloud:
  google_actions:
    filter:
      exclude_domains:
        - automation
        - script
        - group
      exclude_entities:
        - switch.banklampa_sovrum
        - switch.fonsterlampa_sovrum
        - switch.golvlampa_sovrum
        - switch.vardagsrumsfonster
        - media_player.echo_dot_kitchen
        - media_player.this_device
        - media_player.this_device_2
        - media_player.master_bedroom_speaker
        - media_player.chromecast7473
        - media_player.sofias_chromecast
    entity_config:
      light.entrance_ceiling:
        room: Entryway
      light.entrance_table:
        room: Entryway
      light.lantern:
        room: Entryway
      light.bedroom_table:
        room: Bedroom
      light.bedroom_window:
        room: Bedroom
      light.bedroom_floor:
        room: Bedroom
      light.bedroom_ceiling:
        room: Bedroom
      light.living_room_window_lamps:
        room: Living Room
      light.yeelight:
        room: Living Room
      light.living_room_window_right:
        room: Living Room
      light.living_room_window_left:
        room: Living Room
      light.living_room_sofa_table:
        room: Living Room
      light.living_room_ceiling:
        room: Living Room
      light.living_room_ceiling_ikea1:
        room: Living Room
      light.living_room_ceiling_ikea2:
        room: Living Room
      light.bathroom_mirror:
        room: Bathroom
      light.bathroom_ceiling:
        room: Bathroom
      light.sink:
        room: Kitchen
      media_player.echo_dot_kitchen:
        room: Kitchen
        name: Alexa
        aliases:
          - Echo Dot
      light.kitchen_table_ceiling:
        room: Kitchen
      switch.balkong:
        room: Outside
  alexa:
    filter:
      exclude_domains:
        - automation
        - script
        - group
        - sensor
        - alert
      exclude_entities:
        - switch.banklampa_sovrum
        - switch.fonsterlampa_sovrum
        - switch.golvlampa_sovrum
        - switch.vardagsrumsfonster
        - media_player.echo_dot_kitchen
        - media_player.this_device
        - media_player.this_device_2
      include_entities:
        - sensor.kyl_temperature
    entity_config:
      media_player.master_bedroom_speaker:
        name: Google Home
        description: Bedroom
        display_categories: SPEAKER
      media_player.sofias_chromecast:
        name: Chromecast
        description: Bedroom
        display_categories: TV
      sensor.kyl_temperature:
        name: Temperature Refrigerator
        description: Kitchen
        display_categories: TEMPERATURE_SENSOR


group: !include groups.yaml
automation: !include_dir_list automation
script: !include scripts.yaml




plant:
  blomma1:
    sensors:
      moisture: sensor.blomma1_moisture
      battery: sensor.blomma1_battery
      temperature: sensor.blomma1_temperature
      conductivity: sensor.blomma1_conductivity
      brightness: sensor.blomma1_light_intensity
    min_moisture: 7
    max_moisture: 50
    min_battery: 20
    min_conductivity: 50
    max_conductivity: 1000
    min_temperature: 8
    max_temperature: 32
    #min_brightness: 2800
    #max_brightness: 20000
  blomma2:
    sensors:
      moisture: sensor.blomma2_moisture
      battery: sensor.blomma2_battery
      temperature: sensor.blomma2_temperature
      conductivity: sensor.blomma2_conductivity
      brightness: sensor.blomma2_light_intensity
    min_moisture: 20
    max_moisture: 60
    min_battery: 20
    min_conductivity: 50
    max_conductivity: 2000
    min_temperature: 6
    max_temperature: 35
    #min_brightness: 1000
    #max_brightness: 30000
  blomma3:
    sensors:
      moisture: sensor.blomma3_moisture
      battery: sensor.blomma3_battery
      temperature: sensor.blomma3_temperature
      conductivity: sensor.blomma3_conductivity
      brightness: sensor.blomma3_light_intensity
    min_moisture: 15
    max_moisture: 60
    min_battery: 20
    min_conductivity: 50
    max_conductivity: 2000
    min_temperature: 10
    max_temperature: 32
    #min_brightness: 600
    #max_brightness: 20000
  blomma4:
    sensors:
      moisture: sensor.blomma4_moisture
      battery: sensor.blomma4_battery
      temperature: sensor.blomma4_temperature
      conductivity: sensor.blomma4_conductivity
      brightness: sensor.blomma4_light_intensity
    min_moisture: 15
    max_moisture: 60
    min_battery: 20
    min_conductivity: 50
    max_conductivity: 2000
    min_temperature: 12
    max_temperature: 32
    #min_brightness: 800
    #max_brightness: 15000
  blomma5:
    sensors:
      moisture: sensor.blomma5_moisture
      battery: sensor.blomma5_battery
      temperature: sensor.blomma5_temperature
      conductivity: sensor.blomma5_conductivity
      brightness: sensor.blomma5_light_intensity
    min_moisture: 7
    max_moisture: 40
    min_battery: 20
    min_conductivity: 50
    max_conductivity: 2000
    min_temperature: 6
    max_temperature: 35
    #min_brightness: 1000
    #max_brightness: 30000
  blomma6:
    sensors:
      moisture: sensor.blomma6_moisture
      battery: sensor.blomma6_battery
      temperature: sensor.blomma6_temperature
      conductivity: sensor.blomma6_conductivity
      brightness: sensor.blomma6_light_intensity
    min_moisture: 7
    max_moisture: 50
    min_battery: 20
    min_conductivity: 50
    max_conductivity: 1000
    min_temperature: 10
    max_temperature: 32
    #min_brightness: 1500
    #max_brightness: 60000
  blomma7:
    sensors:
      moisture: sensor.blomma7_moisture
      battery: sensor.blomma7_battery
      temperature: sensor.blomma7_temperature
      conductivity: sensor.blomma7_conductivity
      brightness: sensor.blomma7_light_intensity
    min_moisture: 15
    max_moisture: 60
    min_battery: 20
    min_conductivity: 50
    max_conductivity: 2000
    min_temperature: 10
    max_temperature: 35
    #min_brightness: 700
    #max_brightness: 50000
  blomma8:
    sensors:
      moisture: sensor.blomma8_moisture
      battery: sensor.blomma8_battery
      temperature: sensor.blomma8_temperature
      conductivity: sensor.blomma8_conductivity
      brightness: sensor.blomma8_light_intensity
    min_moisture: 15
    max_moisture: 60
    min_battery: 20
    min_conductivity: 50
    max_conductivity: 2000
    min_temperature: 5
    max_temperature: 35
    #min_brightness: 4000
    #max_brightness: 60000



# Telldus Live!
tellduslive:


binary_sensor:
  - platform: flic
#  - platform: mqtt
#    state_topic: dummy/floorplan/sensor
#    name: Floorplan



device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.1-255
    exclude: 192.168.0.41
    home_interval: 10
    consider_home: 1800

vacuum:
  - platform: xiaomi_miio
    host: 192.168.0.26
    token: !secret vacuum_token
    name: Borris

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pb_access_token
  - name: twilio
    platform: twilio_sms
    from_number: '+46769437342'
  - name: notify_everyone
    platform: group
    services:
      - service: twilio
        data:
          target:
            - '+46723239206'
            - '+46703571658'
      - service: pushbullet

media_player:
  - platform: alexa
    email: !secret amazon_email
    password: !secret amazon_password
    url: "amazon.com"

alert:
  bathroom_door:
    name: Åhnej! Katten kan inte komma in i badrummet!
    done_message: Puh! Nu är badrumsdörren öppen igen och katten kan åter bajsa! 
    entity_id: binary_sensor.badrumsdorr
    state: 'off'
    repeat: 10
    can_acknowledge: True
    skip_first: True
    notifiers:
      - notify_everyone
  plant1:
    name: Fd boll behöver omvårdnad
    done_message: Tack, nu mår fd boll bra igen!
    entity_id: plant.blomma1
    state: 'problem'
    repeat: 2880
    can_acknowledge: True
    skip_first: False
    message: "Fd boll behöver omvårdnad med ({{ state_attr('plant.blomma1', 'problem') }})" 
    notifiers:
      - notify_everyone
  plant2:
    name: Candula behöver omvårdnad
    done_message: Tack, nu mår Candula bra igen!
    entity_id: plant.blomma2
    state: 'problem'
    repeat: 2880
    can_acknowledge: True
    skip_first: False
    message: "Candula behöver omvårdnad med ({{ state_attr('plant.blomma2', 'problem') }})" 
    notifiers:
      - notify_everyone
  plant3:
    name: Garderobsblomma behöver omvårdnad
    done_message: Tack, nu mår Garderobsblomma bra igen!
    entity_id: plant.blomma3
    state: 'problem'
    repeat: 2880
    can_acknowledge: True
    skip_first: False
    message: "Garderobsblomma behöver omvårdnad med ({{ state_attr('plant.blomma3', 'problem') }})" 
    notifiers:
      - notify_everyone
  plant4:
    name: Adams revben behöver omvårdnad
    done_message: Tack, nu mår Adams revben bra igen!
    entity_id: plant.blomma4
    state: 'problem'
    repeat: 2880
    can_acknowledge: True
    skip_first: False
    message: "Adams revben behöver omvårdnad med ({{ state_attr('plant.blomma4', 'problem') }})" 
    notifiers:
      - notify_everyone
  plant5:
    name: Påsk kaktusen behöver omvårdnad
    done_message: Tack, nu mår Påsk kaktusen bra igen!
    entity_id: plant.blomma5
    state: 'problem'
    repeat: 2880
    can_acknowledge: True
    skip_first: False
    message: "Påsk kaktusen behöver omvårdnad med ({{ state_attr('plant.blomma5', 'problem') }})" 
    notifiers:
      - notify_everyone
  plant6:
    name: Spindellilja behöver omvårdnad
    done_message: Tack, nu mår Spindellilja bra igen!
    entity_id: plant.blomma6
    state: 'problem'
    repeat: 2880
    can_acknowledge: True
    skip_first: False
    message: "Spindellilja behöver omvårdnad med({{ state_attr('plant.blomma6', 'problem') }})" 
    notifiers:
      - notify_everyone
  plant7:
    name: Palmen behöver omvårdnad
    done_message: Tack, nu mår Palmen bra igen!
    entity_id: plant.blomma7
    state: 'problem'
    repeat: 2880
    can_acknowledge: True
    skip_first: False
    message: "Palmen behöver omvårdnad med ({{ state_attr('plant.blomma7', 'problem') }})" 
    notifiers:
      - notify_everyone
  plant8:
    name: Ostabil blomma behöver omvårdnad
    done_message: Tack, nu mår Ostabil blomma bra igen!
    entity_id: plant.blomma8
    state: 'problem'
    repeat: 2880
    can_acknowledge: True
    skip_first: False
    message: "Ostabil blomma behöver omvårdnad med ({{ state_attr('plant.blomma8', 'problem') }})" 
    notifiers:
      - notify_everyone
