alias: Turn off bathroom light 2 minutes after last movement
trigger:
  platform: state
  entity_id: sensor.badrum_motion_sensor
  to: 'off'
  for:
    minutes: 2
action:
  service: light.turn_off
  entity_id: group.bathroom
