alias: Turn on bathroom light when there is movement
trigger:
  platform: state
  entity_id: sensor.badrum_motion_sensor
  to: 'on'
#  condition:
#    condition: and
#    conditions:
#      - condition: state
#        entity_id: light.bathroom_ceiling
#        state: 'off'
#      - condition: state
#        entity_id: light.bathroom_mirror
#        state: 'off'
action:
  service: light.turn_on
  entity_id: group.bathroom
  data:
    brightness: 100

