alias: Turn off entrance light 2 minutes after last movement
trigger:
  platform: state
  entity_id: binary_sensor.hallsensor_motion
  to: 'off'
  for:
    minutes: 2
action:
  service: light.turn_off
  entity_id: group.entrance
