alias: 'Turn on Entrance light when movement in night'
trigger: 
  platform: state
  entity_id: sensor.motion_hallsensor
  from: 'off'
  to: 'on'
condition:
  condition: time
  after: '22:00:00'
  before: '08:00:00'
action:
  service: light.turn_on
  entity_id:
    - light.entrance_table
    - light.lantern
  data:
    brightness: 50 

