alias: Turn off entrance light 10 minutes after last movement
trigger:
  platform: state
  entity_id: sensor.motion_hallsensor
  to: 'off'
  for:
    minutes: 10
action:
  service: light.turn_off
  entity_id: group.entrance
