alias: Turn off all lights in bedroom if at least on lamp is on, when pressing button
trigger:
  platform: event
  event_type: flic_click
  event_data:
    button_name: flic_80e4da733b73
    click_type: single
condition:
  - condition: state
    entity_id: group.bedroom
    state: 'on'
action:
  - service: homeassistant.turn_off
    entity_id: group.bedroom
  - service: notify.alexa_media
    data:
      target: 
        - "Echo dot Kitchen"
      message: "Good night, sleep well."
      data: 
        type: tts
